twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        limit: '%env(LIMIT_PAGINATION_5)%'
        bonneNote: 3.7
        moyenneNote: 2.4
        maxlength: 500
        maxlength2: 1500
        reduction: 33
when@test:
    twig:
        strict_variables: true
